In [1]:
import numpy as np
import cv2
from tensorflow.keras import models, layers

# Define CNN architecture for feature extraction
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
])

# Chessboard dimensions
board_width = 7  # Number of inner corners along the width
board_height = 7  # Number of inner corners along the height

# Prepare object points, like (0,0,0), (1,0,0), ..., (8,5,0)
objp = np.zeros((board_width*board_height, 3), np.float32)
objp[:, :2] = np.mgrid[0:board_width, 0:board_height].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
objpoints = []  # 3D points in real world space
imgpoints = []  # 2D points in image plane

# Load images and find chessboard corners
images = [
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0000.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0001.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0002.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0003.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0004.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0005.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0006.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0007.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0008.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0009.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0010.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0011.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0012.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0013.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0014.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0015.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0016.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0017.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0018.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0019.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0020.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0021.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0022.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0023.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0024.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0025.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0026.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0027.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0028.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0029.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0030.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0031.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0032.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0033.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0034.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0035.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0036.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0037.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0038.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0039.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0040.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0041.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0042.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0043.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0044.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0045.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0046.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0047.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0048.jpg",
    r"D:\Saved Pictures\chessboard images\original\IMG-20240319-WA0049.jpg",
    ]  # List of chessboard images

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Resize image to fit CNN input shape
    img_resized = cv2.resize(img, (256, 256))
    img_resized = img_resized / 255.0  # Normalize image pixels

    # Extract features using CNN
    features = model.predict(np.expand_dims(img_resized, axis=0))

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (board_width, board_height), None)

    # If found, add object points, image points
    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (board_width, board_height), corners, ret)
        cv2.imshow('corner detected', img)
        cv2.waitKey(0)

cv2.destroyAllWindows()
# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# Print intrinsic parameters (camera matrix and distortion coefficients)
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)

# Print extrinsic parameters (rotation vectors and translation vectors)
for i in range(len(rvecs)):
    print(f"\nExtrinsic parameters for image {i+1}:")
    print("Rotation Vector:")
    print(rvecs[i])
    print("Translation Vector:")
    print(tvecs[i])
    

1/1 [==============================] - 0s 16ms/step
Camera Matrix:
[[1.02360696e+03 0.00000000e+00 4.90697598e+02]
 [0.00000000e+00 1.02973456e+03 6.33054602e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion Coefficients:
[[ 0.09684642 -0.45484659 -0.01356073  0.00052631 -0.116255  ]]

Extrinsic parameters for image 1:
Rotation Vector:
[[-0.32990314]
 [-0.18543369]
 [-0.04604658]]
Translation Vector:
[[-3.34947886]
 [-3.82984464]
 [10.91994046]]

Extrinsic parameters for image 2:
Rotation Vector:
[[-0.01037543]
 [ 0.54514467]
 [ 3.05462447]]
Translation Vector:
[[ 3.10405498]
 [-0.2767511 ]
 [14.28709793]]

Extrinsic parameters for image 3:
Rotation Vector:
[[-0.09188821]
 [-0.07355785]
 [-1.55971456]]
Translation Vector:
[[-3.65826752]
 [ 2.58475163]
 [14.94053055]]

Extrinsic parameters for image 4:
Rotation Vector:
[[-0.06625745]
 [-0.13426646]
 [-0.00419786]]
Translation Vector:
[[-2.95862016]
 [-3.27789133]
 [15.41854474]]

Extrinsic parameters for image 5:
Rotatio