In [3]:
import numpy as np
import cv2
from tensorflow.keras import models, layers

# Define CNN architecture for feature extraction
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
])

# Chessboard dimensions
board_width = 7  # Number of inner corners along the width
board_height = 7  # Number of inner corners along the height

# Prepare object points, like (0,0,0), (1,0,0), ..., (8,5,0)
objp = np.zeros((board_width*board_height, 3), np.float32)
objp[:, :2] = np.mgrid[0:board_width, 0:board_height].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
objpoints = []  # 3D points in real world space
imgpoints = []  # 2D points in image plane

# Load images and find chessboard corners
images = [
    r"D:\Saved Pictures\chessboard images\noise\n1.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n2.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n3.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n4.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n5.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n6.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n7.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n8.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n9.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n10.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n11.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n12.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n13.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n14.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n15.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n16.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n17.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n18.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n19.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n20.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n21.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n22.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n23.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n24.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n25.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n26.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n27.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n28.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n29.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n30.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n31.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n32.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n33.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n34.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n35.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n36.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n37.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n38.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n39.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n40.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n41.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n42.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n43.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n44.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n45.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n46.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n47.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n48.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n49.jpg",
    r"D:\Saved Pictures\chessboard images\noise\n50.jpg"
    ]  # List of chessboard images

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Resize image to fit CNN input shape
    img_resized = cv2.resize(img, (256, 256))
    img_resized = img_resized / 255.0  # Normalize image pixels

    # Extract features using CNN
    features = model.predict(np.expand_dims(img_resized, axis=0))

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (board_width, board_height), None)

    # If found, add object points, image points
    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (board_width, board_height), corners, ret)
        cv2.imshow('corner detected', img)
        cv2.waitKey(0)

cv2.destroyAllWindows()
# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# Print intrinsic parameters (camera matrix and distortion coefficients)
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)

# Print extrinsic parameters (rotation vectors and translation vectors)
for i in range(len(rvecs)):
    print(f"\nExtrinsic parameters for image {i+1}:")
    print("Rotation Vector:")
    print(rvecs[i])
    print("Translation Vector:")
    print(tvecs[i])

1/1 [==============================] - 0s 25ms/step
Camera Matrix:
[[364.80721407   0.         185.22848151]
 [  0.         362.5713594  201.14219322]
 [  0.           0.           1.        ]]

Distortion Coefficients:
[[ 0.06736416 -0.20818135 -0.0147796   0.02701633  0.0900911 ]]

Extrinsic parameters for image 1:
Rotation Vector:
[[-0.34461022]
 [-0.24682742]
 [-0.05356414]]
Translation Vector:
[[-4.00255137]
 [-3.50709861]
 [11.35048559]]

Extrinsic parameters for image 2:
Rotation Vector:
[[-0.10703566]
 [ 0.56514366]
 [ 3.03112703]]
Translation Vector:
[[ 2.07892559]
 [ 0.05699107]
 [15.30623144]]

Extrinsic parameters for image 3:
Rotation Vector:
[[-0.05462968]
 [-0.19527449]
 [-0.00390746]]
Translation Vector:
[[-3.958557  ]
 [-2.83622164]
 [16.0101091 ]]

Extrinsic parameters for image 4:
Rotation Vector:
[[-0.12745527]
 [-0.45905315]
 [-3.08129164]]
Translation Vector:
[[ 2.33479388]
 [ 1.76855302]
 [10.35687561]]

Extrinsic parameters for image 5:
Rotation Vector:
[[-0.773