In [3]:
import numpy as np
import cv2
from tensorflow.keras import models, layers

# Define CNN architecture for feature extraction
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
])

# Chessboard dimensions
board_width = 7  # Number of inner corners along the width
board_height = 7  # Number of inner corners along the height

# Prepare object points, like (0,0,0), (1,0,0), ..., (8,5,0)
objp = np.zeros((board_width*board_height, 3), np.float32)
objp[:, :2] = np.mgrid[0:board_width, 0:board_height].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
objpoints = []  # 3D points in real world space
imgpoints = []  # 2D points in image plane

# Load images and find chessboard corners
images = [
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0050.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0051.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0052.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0053.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0054.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0055.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0056.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0057.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0058.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0059.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0060.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0061.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0062.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0063.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0064.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0065.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0066.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0067.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0069.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0070.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0071.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0072.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0073.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0074.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0075.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0076.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0077.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0078.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0079.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0081.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0082.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0083.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0084.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0085.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0086.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0087.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0088.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0089.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0090.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0091.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0092.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0093.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0094.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0095.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0096.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0097.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0098.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0099.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0101.jpg",
    r"D:\Saved Pictures\chessboard images\rotated\IMG-20240319-WA0102.jpg",
    ]  # List of chessboard images

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Resize image to fit CNN input shape
    img_resized = cv2.resize(img, (256, 256))
    img_resized = img_resized / 255.0  # Normalize image pixels

    # Extract features using CNN
    features = model.predict(np.expand_dims(img_resized, axis=0))

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (board_width, board_height), None)

    # If found, add object points, image points
    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (board_width, board_height), corners, ret)
        cv2.imshow('corner detected', img)
        cv2.waitKey(0)

cv2.destroyAllWindows()
# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# Print intrinsic parameters (camera matrix and distortion coefficients)
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)

# Print extrinsic parameters (rotation vectors and translation vectors)
for i in range(len(rvecs)):
    print(f"\nExtrinsic parameters for image {i+1}:")
    print("Rotation Vector:")
    print(rvecs[i])
    print("Translation Vector:")
    print(tvecs[i])
    

1/1 [==============================] - 0s 31ms/step
Camera Matrix:
[[1.03576182e+03 0.00000000e+00 4.97138093e+02]
 [0.00000000e+00 1.03525476e+03 6.05630709e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion Coefficients:
[[ 1.39680843e-01 -7.18510876e-01 -1.62448244e-02 -3.62843444e-04
   6.32653314e-01]]

Extrinsic parameters for image 1:
Rotation Vector:
[[-0.33343104]
 [-0.637583  ]
 [-0.07179052]]
Translation Vector:
[[-2.39359675]
 [-3.34440828]
 [ 8.21213548]]

Extrinsic parameters for image 2:
Rotation Vector:
[[-0.22432364]
 [-0.49286214]
 [-0.21513312]]
Translation Vector:
[[-2.67976727]
 [-4.51185908]
 [10.42884657]]

Extrinsic parameters for image 3:
Rotation Vector:
[[-0.1806587 ]
 [ 1.00531432]
 [ 2.7415785 ]]
Translation Vector:
[[ 2.65829057]
 [-1.41434063]
 [11.74342326]]

Extrinsic parameters for image 4:
Rotation Vector:
[[-0.17153794]
 [ 0.62817278]
 [ 1.4564696 ]]
Translation Vector:
[[ 1.77619203]
 [-6.55655428]
 [13.71661572]]

Extrinsic parameter